Updated Documentation
minio/minio-java-rest-example pull request #15
Opened 2017-07-10 22:20 UTC by CarterMcClellan

Update to Tomcat v 9 (screenshot)

Update to Minio version 3.0.5 (screenshot)

Indicate IDE is for web development (Eclipse)

In AlbumDao.Java declare url or pass it directly (album.setUrl(minioClient.presignedGetObject(minioBucket, item.objectName(), 60 * 60 * 24))

2017-07-11 16:42 UTC, deekoder approved these changes

2017-07-11 16:49 UTC, nitisht approved these changes
LGTM

2017-07-13 18:30 UTC, deekoder requested changes

2017-07-13 18:30 UTC, deekoder commented on README.md
> +![TomCatv9](docs/screenshots/minio-TomCatv9.png)
Needs to be full path. Otherwise images won't display in play.

2017-07-13 18:30 UTC, deekoder commented on README.md
> +![Dependencies](docs/screenshots/Minio-Dependencies.png)
Needs to be full github path

2017-07-13 18:42 UTC, deekoder requested changes

2017-07-13 18:42 UTC, deekoder commented on README.md
> +![Dependencies](https://github.com/minio/minio-java-rest-example/blob/master/docs/screenshots/Minio-Dependencies.png)
?raw=true is it needed. Maybe /maybe not. Pls confirm.

2017-07-14 18:54 UTC, deekoder requested changes

2017-07-14 18:54 UTC, deekoder commented on README.md
> +			<version>3.0.5</version>
change to 3.0.6

2017-07-15 00:22 UTC, harshavardhana requested changes

2017-07-15 00:22 UTC, harshavardhana commented on README.md
> -![minio_JAVA5](https://github.com/minio/minio-java-rest-example/blob/master/docs/screenshots/minio-JAVA5.jpg?raw=true)
You should also remove this file from the repo.

2017-07-15 00:22 UTC, harshavardhana commented on README.md
> +![TomCatv9](https://github.com/minio/minio-java-rest-example/blob/master/docs/screenshots/minio-TomCatv9.png)
Lets use tomcat v8.5.16.

2017-07-18 03:52 UTC, closed without merging